version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - IncPlusPlus
  assignees:
  - IncPlusPlus
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - IncPlusPlus
  assignees:
  - IncPlusPlus
  ignore:
  - dependency-name: ch.obermuhlner:big-math
    versions:
    - ">= 2.1.a, < 2.2"
  - dependency-name: org.apache.commons:commons-lang3
    versions:
    - ">= 3.9.a, < 3.10"
  - dependency-name: org.apache.maven.plugins:maven-compiler-plugin
    versions:
    - "> 3.8.0, < 3.9"
  - dependency-name: org.apache.maven.plugins:maven-failsafe-plugin
    versions:
    - "> 2.22.0, < 2.23"
  - dependency-name: org.apache.maven.plugins:maven-source-plugin
    versions:
    - ">= 3.1.a, < 3.2"
  - dependency-name: org.apiguardian:apiguardian-api
    versions:
    - ">= 1.1.a, < 1.2"
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - "> 5.4.0, < 5.5"
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - ">= 5.5.a, < 5.6"
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - "> 5.4.0, < 5.5"
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - ">= 5.5.a, < 5.6"
  - dependency-name: org.junit.platform:junit-platform-commons
    versions:
    - "> 1.4.0, < 1.5"
  - dependency-name: org.junit.platform:junit-platform-commons
    versions:
    - ">= 1.5.a, < 1.6"
  - dependency-name: org.opentest4j:opentest4j
    versions:
    - ">= 1.2.a, < 1.3"
