name-template: '$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
branches:
  - master
  - develop
exclude-labels:
  - 'skip-changelog'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐞 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🐛 Security Vuln. Fixes'
    label: 'security vulnerability'
  - title: '🛠 Improvements'
    label: '🛠 Improvement'
  - title: '📖 Documentation'
    label: '📖 Docs'
  - title: '📚 Dependencies'
    label: 'dependencies'
  - title: '🧰 Maintenance'
    label: 'chore'
    
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  $CHANGES
  ***
  For full changes, see the [comparison between $PREVIOUS_TAG and $NEXT_MINOR_VERSION](https://github.com/IncPlusPlus/bigtoolbox/compare/$PREVIOUS_TAG...$NEXT_MINOR_VERSION)
