name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
branches: master, develop
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐞 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🐛 Security Vuln. Fixes'
    label: 'security vulnerability'
  - title: '🛠 Improvements'
    label: '🛠 Improvement'
  - title: '📖 Documentation'
    label: '📖 Docs'
  - title: '📚 Dependencies'
    label: 'dependencies'
  - title: '🧰 Maintenance'
    label: 'chore'
    
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  $CHANGES
  ***
  For full changes, see the [comparison between $PREVIOUS_TAG and v$NEXT_MINOR_VERSION](https://github.com/IncPlusPlus/bigtoolbox/compare/$PREVIOUS_TAG...v$NEXT_MINOR_VERSION)
