language: java
sudo: false
install: true
jdk:
- oraclejdk8
- openjdk8
addons:
  sonarcloud:
    organization: "incplusplus-github"
    token: SONAR_TOKEN
script:
- mvn clean install org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar
