dist: xenial
language: java
env:
- CLI_VERSION=latest
addons:
  apt:
    sources:
    - sourceline: deb https://download.mono-project.com/repo/ubuntu stable-xenial
        main
      key_url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xA6A19B38D3D831EF
    packages:
    - mono-devel
    - mono-xbuild
    - msbuild
    - libmono-system-runtime-interopservices-runtimeinformation4.0-cil
matrix:
  include:
  - jdk: oraclejdk11
    script: "./gradlew clean build"
  - jdk: oraclejdk11
    script:
    - which mono
    - mvn clean install
    deploy:
    - provider: bintray
      file: bintray_info_maven.JSON
      user: incplusplus
      key: "$bintray_key"
      skip_cleanup: true
      on:
        branch: develop
    - provider: releases
      api_key:
        secure: m15GsZRwD8KK6Nwm7iurq1PLcQSO0XJaRZTUa9k+Ss2FBt26dGk4uOnbbWZLEXDggIF0MWhYWtIc58ZvkVP9p46PSScuYw33ogqeMXKVwXmM5n+jLchnurac7/+XbX8Im3QxFSnZSsNm67vcrDJaNBeI+ZhiBt7CU1e2eZJAQK5jc2gZM0enTomQoRF9tGV3uHopo2elEte1mMFdNGPjXFz6ZZdsbfoNmBEMV1aUAYfJgH+x+g9+1R4II+hSCeLa+4PRckVjx2kDHTsHAZgfI3P+d44qVkJmn3XoT6khUMBDHcf0OtBSvFkZnUxJwvH7ZSf6MpV5bW1SfoKnWcMkaECqkzVYyhmlcSUfN0cjtVP9mc11L2DkNTarHR67v+zPizkk8ZlLPaW74z6cTF4YwAXngMX6bl1lS4ksQYhDxHTztZFmnAQME8oSeqbyChooRzME6jGlQ5fwJnpZ+IEOvac7s/cnPrhCSL1ay+oSsznGFvcvXrlVvv9RUnxqMQP9nEDnX9ne8ttIuVSROJd0M03jLBfmnlrFDvtM2zxiyOWv/F9QZUHOC3NUPPMgh0bFTfwwm8NzvBjd1sa6YA9gjfYrLC32bhI9YmbWItm4F6fV4DLmIOXpTHd47JRLqU2Vos+VKNOJPib5kiz7DSWE5iyF1k2o4PhJasNgbAU54rk=
      file: bigtoolbox-*.*.*.jar
      on:
        repo: IncPlusPlus/bigtoolbox
        branch: hotfix/improve_travis_build_performance
  - jdk: openjdk11
    script: "./gradlew clean build"
  - jdk: openjdk11
    script: mvn clean install
