language: java
jdk:
- oraclejdk8
- openjdk8
addons:
  sonarcloud:
    organization: incplusplus-github
    token:
      secure: EBqayX6oQL0ImNWlbZw5ztaGwWPHYNk/cPhTFE6qLgkNVlN+OfaNmIDCmd3OmbetrLZ9uR0OuVtgbEAWa532mgddnGmNnR2843U1EQuA1DIV/REV0fXApE+5sHv+snee7sUVh8Sz5Ckpuy/aB4G+U6dibaTkZ2/jja7XGu5qWr2b7OgTD3lDCVntCZfcgsA3RiInlBTBL7tlx9OzHttjNIS7jdX3oRDWLdVqJaFiTByt4XLH2WKjaFX55inBCPlK9L6tZwFsy3vOMwAk+Y5JXre0hbEw0zq96E9pEsLOpVwzZRvKGRYU2siWbde+NaJAcVXPm447qoYyIpjxruXNNNr74OXReglzxnvWD+T0lsxz7yjte3s0B4ffiO/HLqfIBNQ3m42p3amRR1nr92oXzAXyLBjwF+7IQVvxyHD0n00N1NjIsauSbsVzBbwqESGhOTCxu+075xvlI0oTVwSVuJOWO/Mf2hVhEetIXODatjxiGauhaCxKHYlIU67rg6voywYXHmo0sr6GaxmPMZhstFMnELYHlMTuO+qWQ3KNfbuLBUMyaoIuVqpNRkiJhP4nve/dqi48eeq++7QUQdcmlIjlmeSE+2MBao0g78ySCMoXWKchpgbOwUyaIutxDmY9QRIMlQ0TynKEd1zO3UNCpSfG2SUT4ioY9a/4VdwfU0E=
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
