dist: xenial
language: java
jdk:
- oraclejdk11
- openjdk11
env:
- CLI_VERSION=latest
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
    - nuget
before_script:
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
- sudo apt install apt-transport-https ca-certificates
- echo "deb https://download.mono-project.com/repo/ubuntu stable-xenial main" | sudo
  tee /etc/apt/sources.list.d/mono-official-stable.list
- sudo apt update
- sudo apt install mono-complete msbuild -y
- chmod +x gradlew
install:
- export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
- curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh
  | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
- export PATH="$DOTNET_INSTALL_DIR:$PATH"
matrix:
  include:
  - script: "./gradlew clean build"
  - script: mvn clean verify
deploy:
  on:
    all_branches: true
  provider: bintray
  file: bintray_info.JSON
  user: incplusplus
  key:
    secure: m0LGybmXxm6GBRKo70Js/6kddEH8uqoGXgcpr8AWt8a12Wb8U5eOkQPReKAYVDbDuQ+4rY8xAnHUONTGqS1MaT/z53nx7eCJhuCB1hHEegyHqEvppRSKUgTSLVeIbIm6njEaB5Yxg25krvjYGtYLdDB89LY8MojeyHN92l8X5cu/E/xetpd0TTaCWRC7zRValWEMTroNsUFdlfIr0m+MRfc+EVbBirnqFQuSPnJ1i2Bzic8YI+sch0rTCVDne5gfQIJbx/VB72DOr15009xKfQCPz29n7YufxTSwucEmJaNHGirwKJvijUm7i2JBHMb8RuLcmFcKzKhQFVe9KwCqLGpnctMOKqqOF0hAv77FzPQqbozxROoZBzr3+wbiFp1TDYAIJcpkkIh93GOVkmG53Ca1esHteI7CwGh46Imbc2OzvcN1qQUfdwNbCzQgO7CFMY6puOsftlqa5LxRmLXvmJnHP1gq9QCXBaJEziNW8V+k8JJ+5F6ARSAL2608OCnkwBPJ1bERRM4MCvzYkusls9fUf/ap1QGv4+vwOpy5V7efeuxX6OGoFTQJjQJaBZGljMF4hsSQ+Nu1nDG8pCbq7lY5GD2COY2PLnH8yhL/HD7laWCT/eqE1KXTkYpOT87ADxOmGeYI/FcMuIn9wB+PF7wm4KJ9VNmKWX7pOODL1ls=
  skip_cleanup: true

