name: Release Management

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master

jobs:
  update_draft_release:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: toolmantim/release-drafter@v5.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name-template: 'v$NEXT_PATCH_VERSION 🌈'
        tag-template: 'v$NEXT_PATCH_VERSION'
        categories:
          - title: '🚀 Features'
            labels:
              - 'feature'
              - 'enhancement'
          - title: '🐛 Bug Fixes'
            labels:
              - 'fix'
              - 'bugfix'
              - 'bug'
          - title: '🧰 Maintenance'
            label: 'chore'
        change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
        template: |
          ## Changes

          $CHANGES
